"""create initial tender review schema

Revision ID: 6163370fb844
Revises:
Create Date: 2026-07-27 16:38:52.909165
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6163370fb844"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=255), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column(
            "media_type",
            sa.String(length=255),
            server_default="application/pdf",
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "parse_status",
            sa.String(length=32),
            server_default="UPLOADED",
            nullable=False,
        ),
        sa.Column("parser_name", sa.String(length=128), nullable=True),
        sa.Column("parser_version", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "parse_status IN ('UPLOADED', 'PARSING', 'PARSED', 'FAILED')",
            name=op.f("ck_document_snapshots_parse_status"),
        ),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_document_snapshots_size_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_snapshots")),
        sa.UniqueConstraint("sha256", name=op.f("uq_document_snapshots_sha256")),
        sa.UniqueConstraint(
            "source_system",
            "source_document_id",
            name=op.f("uq_document_snapshots_source_system"),
        ),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("caller_id", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "caller_id",
            "scope",
            "idempotency_key",
            name="uq_idempotency_caller_scope_key",
        ),
    )
    op.create_index(
        "ix_idempotency_records_resource",
        "idempotency_records",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "model_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_configs")),
        sa.UniqueConstraint("config_hash", name=op.f("uq_model_configs_config_hash")),
    )
    op.create_table(
        "rule_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_sets")),
        sa.UniqueConstraint("rule_key", name=op.f("uq_rule_sets_rule_key")),
    )
    op.create_table(
        "document_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_document_artifacts_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["document_snapshot_id"],
            ["document_snapshots.id"],
            name=op.f("fk_document_artifacts_document_snapshot_id_document_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_artifacts")),
        sa.UniqueConstraint(
            "document_snapshot_id",
            "artifact_type",
            "object_key",
            name=op.f("uq_document_artifacts_document_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_document_artifacts_object",
        "document_artifacts",
        ["bucket", "object_key"],
        unique=False,
    )
    op.create_table(
        "rule_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_set_id", sa.String(length=36), nullable=False),
        sa.Column("parent_version_id", sa.String(length=36), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="DRAFT", nullable=False
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("execution_config_json", sa.JSON(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'OPTIMIZING', 'EVALUATING', 'WAITING_APPROVAL', 'PUBLISHED', 'REJECTED', 'ROLLED_BACK')",
            name=op.f("ck_rule_versions_status"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_rule_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_rule_versions_parent_version_id_rule_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["rule_sets.id"],
            name=op.f("fk_rule_versions_rule_set_id_rule_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_versions")),
        sa.UniqueConstraint(
            "rule_set_id", "content_hash", name="uq_rule_versions_set_content_hash"
        ),
        sa.UniqueConstraint(
            "rule_set_id", "version_number", name="uq_rule_versions_set_version"
        ),
    )
    _create_rule_set_current_version_fk()
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_name", sa.String(length=255), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("split_strategy_json", sa.JSON(), nullable=False),
        sa.Column("manifest_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "source_type IN ('REAL', 'SYNTHETIC', 'MIXED')",
            name=op.f("ck_dataset_versions_source_type"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_dataset_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"],
            ["document_artifacts.id"],
            name=op.f("fk_dataset_versions_manifest_artifact_id_document_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint(
            "dataset_name", "version_number", name="uq_dataset_versions_name_version"
        ),
        sa.UniqueConstraint(
            "manifest_hash", name=op.f("uq_dataset_versions_manifest_hash")
        ),
    )
    op.create_table(
        "review_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=False),
        sa.Column("model_config_id", sa.String(length=36), nullable=False),
        sa.Column("rerun_of_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="QUEUED", nullable=False
        ),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_stage", sa.String(length=32), nullable=True),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "stage IS NULL OR stage IN ('PARSING', 'INDEXING', 'RETRIEVING', 'EXTRACTING', 'COMPARING', 'VERIFYING', 'REPORTING')",
            name=op.f("ck_review_jobs_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'WAITING_HUMAN', 'COMPLETED', 'RETRY_WAIT', 'FAILED', 'DEAD', 'CANCELLED')",
            name=op.f("ck_review_jobs_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts > 0 AND attempt_count <= max_attempts",
            name=op.f("ck_review_jobs_attempt_counts"),
        ),
        sa.CheckConstraint(
            "lease_token >= 0", name=op.f("ck_review_jobs_lease_token_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["document_snapshot_id"],
            ["document_snapshots.id"],
            name=op.f("fk_review_jobs_document_snapshot_id_document_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["model_configs.id"],
            name=op.f("fk_review_jobs_model_config_id_model_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rerun_of_id"],
            ["review_jobs.id"],
            name=op.f("fk_review_jobs_rerun_of_id_review_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_review_jobs_rule_version_id_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_jobs")),
    )
    op.create_index(
        "ix_review_jobs_input_fingerprint",
        "review_jobs",
        ["input_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_review_jobs_queue",
        "review_jobs",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "evaluation_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("document_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("case_key", sa.String(length=255), nullable=False),
        sa.Column("review_item", sa.String(length=128), nullable=False),
        sa.Column("split", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("expected_compliant", sa.Boolean(), nullable=True),
        sa.Column("expected_finding_json", sa.JSON(), nullable=False),
        sa.Column("expected_evidence_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "source_type IN ('REAL', 'SYNTHETIC', 'EXTERNAL_PLATFORM')",
            name=op.f("ck_evaluation_cases_source_type"),
        ),
        sa.CheckConstraint(
            "split IN ('OPTIMIZATION', 'VALIDATION', 'FROZEN_TEST')",
            name=op.f("ck_evaluation_cases_split"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_evaluation_cases_dataset_version_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_snapshot_id"],
            ["document_snapshots.id"],
            name=op.f("fk_evaluation_cases_document_snapshot_id_document_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_cases")),
        sa.UniqueConstraint(
            "dataset_version_id", "case_key", name="uq_evaluation_cases_dataset_case"
        ),
    )
    op.create_index(
        "ix_evaluation_cases_dataset_split",
        "evaluation_cases",
        ["dataset_version_id", "split"],
        unique=False,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=False),
        sa.Column("model_config_id", sa.String(length=36), nullable=False),
        sa.Column("report_artifact_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("retriever_version", sa.String(length=128), nullable=False),
        sa.Column("code_version", sa.String(length=128), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_evaluation_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_evaluation_runs_dataset_version_id_dataset_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["model_configs.id"],
            name=op.f("fk_evaluation_runs_model_config_id_model_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_artifact_id"],
            ["document_artifacts.id"],
            name=op.f("fk_evaluation_runs_report_artifact_id_document_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_evaluation_runs_rule_version_id_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_index(
        "ix_evaluation_runs_dataset_created",
        "evaluation_runs",
        ["dataset_version_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_job_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=False),
        sa.Column("review_item", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="OPEN", nullable=False
        ),
        sa.Column("compliant", sa.Boolean(), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("explanation_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'NEED_MORE_EVIDENCE', 'WAITING_HUMAN', 'APPROVED', 'REJECTED', 'MODIFIED')",
            name=op.f("ck_findings_status"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_findings_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["review_job_id"],
            ["review_jobs.id"],
            name=op.f("fk_findings_review_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_findings_rule_version_id_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(
        "ix_findings_job_item",
        "findings",
        ["review_job_id", "review_item"],
        unique=False,
    )
    op.create_table(
        "job_checkpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("review_job_id", sa.String(length=36), nullable=False),
        sa.Column("node_name", sa.String(length=128), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("lease_token", sa.Integer(), nullable=False),
        sa.Column("output_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("state_json", sa.JSON(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "lease_token >= 0", name=op.f("ck_job_checkpoints_lease_token_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["output_artifact_id"],
            ["document_artifacts.id"],
            name=op.f("fk_job_checkpoints_output_artifact_id_document_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["review_job_id"],
            ["review_jobs.id"],
            name=op.f("fk_job_checkpoints_review_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_checkpoints")),
        sa.UniqueConstraint(
            "review_job_id", "node_name", name="uq_job_checkpoints_job_node"
        ),
    )
    op.create_table(
        "optimization_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("base_rule_version_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_rule_version_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("current_round", sa.Integer(), server_default="0", nullable=False),
        sa.Column("root_cause", sa.String(length=64), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_optimization_jobs_status"),
        ),
        sa.CheckConstraint(
            "max_rounds > 0 AND current_round >= 0 AND current_round <= max_rounds",
            name=op.f("ck_optimization_jobs_rounds"),
        ),
        sa.ForeignKeyConstraint(
            ["base_rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_optimization_jobs_base_rule_version_id_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_rule_version_id"],
            ["rule_versions.id"],
            name=op.f("fk_optimization_jobs_candidate_rule_version_id_rule_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_optimization_jobs_dataset_version_id_dataset_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_jobs")),
    )
    op.create_table(
        "evidence_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("document_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_id", sa.String(length=128), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(length=1024), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("bbox_json", sa.JSON(), nullable=True),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "page_end >= page_start", name=op.f("ck_evidence_references_page_range")
        ),
        sa.CheckConstraint(
            "page_start > 0", name=op.f("ck_evidence_references_page_start_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_snapshot_id"],
            ["document_snapshots.id"],
            name=op.f("fk_evidence_references_document_snapshot_id_document_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_evidence_references_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_references")),
    )
    op.create_index(
        "ix_evidence_references_document_chunk",
        "evidence_references",
        ["document_snapshot_id", "chunk_id"],
        unique=False,
    )
    op.create_table(
        "human_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("supersedes_decision_id", sa.String(length=36), nullable=True),
        sa.Column("reviewer_id", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("modified_finding_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "decision IN ('APPROVE', 'REJECT', 'MODIFY', 'INSUFFICIENT_EVIDENCE')",
            name=op.f("ck_human_decisions_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_human_decisions_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_decision_id"],
            ["human_decisions.id"],
            name=op.f("fk_human_decisions_supersedes_decision_id_human_decisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_decisions")),
    )
    op.create_index(
        "ix_human_decisions_finding_created",
        "human_decisions",
        ["finding_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "optimization_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("optimization_job_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_rule_version_id", sa.String(length=36), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("root_cause", sa.String(length=64), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evaluation_result_json", sa.JSON(), nullable=False),
        sa.Column("accepted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "schema_version", sa.String(length=16), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_optimization_attempts_attempt_positive")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_rule_version_id"],
            ["rule_versions.id"],
            name=op.f(
                "fk_optimization_attempts_candidate_rule_version_id_rule_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["optimization_job_id"],
            ["optimization_jobs.id"],
            name=op.f("fk_optimization_attempts_optimization_job_id_optimization_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_attempts")),
        sa.UniqueConstraint(
            "optimization_job_id",
            "attempt_number",
            name="uq_optimization_attempts_job_number",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("optimization_attempts")
    op.drop_table("human_decisions")
    op.drop_table("evidence_references")
    op.drop_table("optimization_jobs")
    op.drop_table("job_checkpoints")
    op.drop_table("findings")
    op.drop_table("evaluation_runs")
    op.drop_table("evaluation_cases")
    op.drop_table("review_jobs")
    op.drop_table("dataset_versions")
    _drop_rule_set_current_version_fk()
    op.drop_table("rule_versions")
    op.drop_table("document_artifacts")
    op.drop_table("rule_sets")
    op.drop_table("model_configs")
    op.drop_table("idempotency_records")
    op.drop_table("document_snapshots")
    # ### end Alembic commands ###


def _create_rule_set_current_version_fk() -> None:
    constraint_name = "fk_rule_sets_current_version_id_rule_versions"
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("rule_sets", recreate="always") as batch_op:
            batch_op.create_foreign_key(
                constraint_name,
                "rule_versions",
                ["current_version_id"],
                ["id"],
                ondelete="SET NULL",
            )
        return
    op.create_foreign_key(
        constraint_name,
        "rule_sets",
        "rule_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def _drop_rule_set_current_version_fk() -> None:
    constraint_name = "fk_rule_sets_current_version_id_rule_versions"
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("rule_sets", recreate="always") as batch_op:
            batch_op.drop_constraint(constraint_name, type_="foreignkey")
        return
    op.drop_constraint(constraint_name, "rule_sets", type_="foreignkey")
