from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from .a7 import (
    A7AdmissionReport,
    A7EvidenceBundle,
    FrozenA7ThresholdPolicy,
    assess_evidence,
    create_not_run_plan,
    load_report,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="A7 real-load evidence and technology-admission gate"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    plan = subparsers.add_parser(
        "plan", help="render the fixed 60-cell matrix as explicit NOT_RUN evidence"
    )
    plan.add_argument("--output", type=Path)

    assess = subparsers.add_parser(
        "assess",
        help="validate real evidence and make a conservative admission decision",
    )
    assess.add_argument("--evidence", type=Path)
    assess.add_argument("--threshold-policy", type=Path)
    assess.add_argument("--output", type=Path)

    verify = subparsers.add_parser(
        "verify-report", help="verify hashes and display an existing report read-only"
    )
    verify.add_argument("--report", required=True, type=Path)

    schema = subparsers.add_parser("schema", help="render a strict JSON Schema")
    schema.add_argument(
        "kind", choices=("evidence", "threshold-policy", "report", "plan")
    )
    schema.add_argument("--output", type=Path)
    return parser


def _read_model(path: Path, model_type: type[Any]) -> Any:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return model_type.model_validate(payload)


def _write(payload: Any, output: Path | None) -> None:
    serialized = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    if output is None:
        sys.stdout.write(serialized)
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(serialized, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "plan":
            _write(create_not_run_plan(), args.output)
            return 0
        if args.command == "assess":
            evidence = (
                _read_model(args.evidence, A7EvidenceBundle) if args.evidence else None
            )
            policy = (
                _read_model(args.threshold_policy, FrozenA7ThresholdPolicy)
                if args.threshold_policy
                else None
            )
            report = assess_evidence(
                evidence,
                policy,
                trusted_attestation_key=os.environ.get(
                    "TENDER_REVIEW_A7_ATTESTATION_KEY"
                ),
                trusted_attestation_key_id=os.environ.get(
                    "TENDER_REVIEW_A7_ATTESTATION_KEY_ID"
                ),
            )
            _write(report.model_dump(mode="json"), args.output)
            return 0 if report.claims_allowed else 2
        if args.command == "verify-report":
            report = load_report(
                args.report,
                trusted_attestation_key=os.environ.get(
                    "TENDER_REVIEW_A7_ATTESTATION_KEY"
                ),
                trusted_attestation_key_id=os.environ.get(
                    "TENDER_REVIEW_A7_ATTESTATION_KEY_ID"
                ),
            )
            _write(report.model_dump(mode="json"), None)
            return 0
        schema_types = {
            "evidence": A7EvidenceBundle,
            "threshold-policy": FrozenA7ThresholdPolicy,
            "report": A7AdmissionReport,
        }
        if args.kind == "plan":
            payload = {
                "description": "A7 plan is generated by the plan command and is always NOT_RUN.",
                "report_schema": A7AdmissionReport.model_json_schema(),
                "evidence_schema": A7EvidenceBundle.model_json_schema(),
            }
        else:
            payload = schema_types[args.kind].model_json_schema()
        _write(payload, args.output)
        return 0
    except (OSError, json.JSONDecodeError, ValidationError, ValueError) as exc:
        sys.stderr.write(f"A7_EVIDENCE_REJECTED: {exc}\n")
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
